### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by onedrawingperday** [GjjvdBurg/HugoPhotoSwipe#11]
Hi!

I'm getting the following error while trying to install HugoPhotoSwipe on Ubuntu 16.04
`Could not find a version that satisfies the requirement smartcrop>=0.1 (from hugophotoswipe) (from versions: )
No matching distribution found for smartcrop>=0.1 (from hugophotoswipe)`

I have already installed smartcrop.js using `npm install smartcrop`

What am I doing wrong?

**Comment by GjjvdBurg** [comment]
Hi there!

What command did you use to install HugoPhotoSwipe? Make sure to use the following:

     pip install --process-dependency-links hugophotoswipe

This should install the SmartCrop.py dependency correctly. The SmartCrop.js installation is separate from the Python installation of HugoPhotoSwipe, and is optional.

**Comment by onedrawingperday** [comment]
Yes I used that exact command.

Here is the full output:

```
pip install --process-dependency-links hugophotoswipe
Collecting hugophotoswipe
Collecting six (from hugophotoswipe)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting pyyaml (from hugophotoswipe)
Collecting smartcrop>=0.1 (from hugophotoswipe)
  Could not find a version that satisfies the requirement smartcrop>=0.1 (from hugophotoswipe) (from versions: )
No matching distribution found for smartcrop>=0.1 (from hugophotoswipe)
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
I installed pip through the Ubuntu apt repositories and naturally it's not the latest version.

**Comment by onedrawingperday** [comment]
Upon further investigation it seems that the above command has installed everything under
`/home/$USER/.local/lib/python2.7/site-packages` including `smartcrop.py`

However running the command `hps init` in a directory full of photos gives me the following
`hps: command not found`

It seems that something is wrong with my setup.

**Comment by GjjvdBurg** [comment]
In this case the ``hps`` executable is probably installed in the directory ``/home/$USER/.local/bin/``. If this is the case, you can add this directory to your ``PATH`` variable by adding the following in your ``~/.bashrc``:

    export PATH=$PATH:$HOME/.local/bin/

don't forget to source your ``~/.bashrc`` after editing it, with: ``source ~/.bashrc``. Hope this helps!

**Comment by onedrawingperday** [comment]
Oh! Yes. That was my problem. `hps` was not on my `PATH` because I didn't install it as root. 

However I solved my problem before you posted the above comment by uninstalling `hugoswipe` and `pip` and then reinstalling them as root.

Now I can run the `hps init` command properly. Thank you for HugoPhotoSwipe! It seems very cool and finally I can start testing it properly.

**Comment by GjjvdBurg** [comment]
Glad you solved it @onedrawingperday, hope that HugoPhotoSwipe is useful to you!
