### ISSUE TITLE
Suggestion for image size detection

### ISSUE THREAD

**Issue by onedrawingperday** [GjjvdBurg/HugoPhotoSwipe#12]
Hello again!

Since Hugo 0.19 there is a new imageConfig function to detect an image's size.
[](https://gohugo.io/templates/functions/#imageconfig)

Maybe you want to integrate it with HugoSwipe since imageConfig is native to Hugo.

Here is an example shortcode that works for me:

```
    <figure>
    {{ $src := .Get "src" }}
    {{ $config := imageConfig (printf "/static/%s" $src) }}
    <img src="{{ $.Page.Site.BaseURL }}{{ .Get "src" }}" alt="{{ .Get "title" }}" {{ if or (.Get "alt") (.Get "caption") }}alt="{{ with .Get "alt"}}{{.}}{{else}}{{ .Get "caption" }}{{ end }}"{{ end }} height="{{$config.Height}}" width="{{$config.Width}}" />
    </figure>
```

And on each markdown I use it like so:

    `{{< img src="PATH TO IMAGE" title="Lorem Ipsum">}}`

**Comment by GjjvdBurg** [comment]
Thanks for the suggestion! What would be the advantage of this exactly? HugoPhotoSwipe already encodes the size of the images in the shortcode, right?

**Comment by onedrawingperday** [comment]
It's all a matter of what you prefer to do. 

Of course HugoPhotoSwipe encodes the image size in the shortcode and in the filename (as I've seen first hand). But in case you want to let Hugo handle image dimensions on publish without encoding dimensions in the shortcode you now have the imageConfig option to handle it.

Also someone on the Hugo forums has posted a shortcode to call images from a folder with scrset.
If interested see: [https://discuss.gohugo.io/t/shortcode-to-generate-images-with-srcset/5812](https://discuss.gohugo.io/t/shortcode-to-generate-images-with-srcset/5812)

And again thank you for your script! It's a time saver!

**Comment by GjjvdBurg** [comment]
I'm going to close this for now. However, in the future it might be a nice feature to let the user define their own shortcode, which would allow them to use this ``imageConfig`` feature of Hugo if they want to. 

Thanks again for the suggestion!
