### ISSUE TITLE
Request: Ability to set image width instead of max dimension

### ISSUE THREAD

**Issue by onedrawingperday** [GjjvdBurg/HugoPhotoSwipe#13]
Again thank you for the great script. It's a super time saver and I really appreciate it.

But is there a way to set the width instead of the max dimension on image resize?

For example when I set dim_max_large to 1920 in `hugophotoswipe.yml` I would like it to output images that are 1920 px wide.

**Comment by onedrawingperday** [comment]
I see that you started to work on this.

Just a clarification. You don't need to change the existing behavior. 

I think that it would be best if you added a new parameter for `hugophotoswipe.yml` something like width_as_max_dim

Again my thanks!

**Comment by GjjvdBurg** [comment]
This is now possible in version 0.0.15, sorry it took so long. See the updated documentation for instructions on how to use the new feature. I've chosen to make the ``dim_max_`` options a bit more flexible, with a format that allows for a constant height, constant width, or specific image size. This also allows me to remove the ``square_thumbnails`` and ``square_coverimage`` settings.

Let me know if you have questions!

**Comment by onedrawingperday** [comment]
Thank you so very much! I'll check it out as soon as I can.
