### ISSUE TITLE
improve HugoPhotoSwipe-Demo using phugo theme

### ISSUE THREAD

**Issue by jujes** [GjjvdBurg/HugoPhotoSwipe#16]
Hi, I successes setup all but need use it inside a real theme, I found phugo theme:
https://github.com/aerohub/phugo and need know how use it in HugoPhotoSwipe

Someone can tell me how use this theme?
here the demo site:
http://themes.gohugo.io/theme/phugo/

instead:
https://gjjvdburg.github.io/HugoPhotoSwipe-Demo/

thanks in advance,

**Comment by GjjvdBurg** [comment]
Hi @jujes, thanks for checking out HugoPhotoSwipe! From a brief look at the phugo source it seems like there are at least two things you need to change to make it work. First, phugo uses a ``photo`` shortcode which is different than that used by HugoPhotoSwipe. To make it work, you might be able to change the ``photo`` shortcode to work with the output of HugoPhotoSwipe. You can read more about shortcodes in Hugo [here](https://gohugo.io/extras/shortcodes/). Second, phugo uses a ``albumthumb`` key in the TOML part of the album markdown file. You will have to make sure that this points to the cover image generated by HugoPhotoSwipe. This can be done using the instructions [here](https://github.com/GjjvdBurg/HugoPhotoSwipe/wiki#custom-fields-in-the-toml).

I hope this helps! Let me know if you have further questions.
