### ISSUE TITLE
where I can get the photography theme?

### ISSUE THREAD

**Issue by jujes** [GjjvdBurg/HugoPhotoSwipe#20]
Hi, someone know if possible get the theme of gertjanvandenburg.com?

thanks in advance,

**Comment by jee-r** [comment]
I'm also interested.
It's look like a custom bootstrap theme.
There are so few dark themes for hugo @GjjvdBurg if you can publish somewhere your theme you will be my (our) hero.

Ps: Thank's for HugoPhotoSwipe it's an awesome tool <3

**Comment by GjjvdBurg** [comment]
@jujes and @flip-bs, thanks for your interest in the theme of my site! It's not currently available as a hugo theme (it's mostly handwritten), but I'll look into making it available as a theme (no promises!)

**Comment by GjjvdBurg** [comment]
@jujes and @flip-bs, I've written [a blog post](https://gertjanvandenburg.com/blog/how_I_made/) which describes some aspects of the theme of the site, as making it available as a full Hugo theme is not a priority for me right now. The blog post should be sufficient to get you started on making your own site. Good luck!
