### ISSUE TITLE
NameError: name *** is not defined

### ISSUE THREAD

**Issue by bradryanbice** [GjjvdBurg/HugoPhotoSwipe#23]
I'm getting an error when trying to set up a new (initial) album.

I've followed the install steps exactly (though I'm unsure about where the photos markdown and output directories should live within the hugo structure, but nonetheless...) and am now on the create new album step. Here is what I am using on the command line, under root/hugophotos:

```
hugophotos git:(master) ✗ hps new
Please provide a name for the new album: photos-work
Traceback (most recent call last):
  File "/usr/local/bin/hps", line 12, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/hugophotoswipe/ui.py", line 38, in main
    hps.new(name=album)
  File "/Library/Python/2.7/site-packages/hugophotoswipe/hugophotoswipe.py", line 40, in new
    name = input("Please provide a name for the new album: ")
  File "<string>", line 1, in <module>
NameError: name 'photos' is not defined
```

Any idea what i may be doing wrong here? I haven't seen anyone else with the same issue so it's most likely my fault or my environment. I've also tried shorter names for the album like "work".

**Comment by GjjvdBurg** [comment]
Hi @bradryanbice, thanks for reporting this! This was indeed a bug in HPS for Python 2. I've updated it now so it should work if you update to the newest version (0.2.1). 

With regards to the photos markdown and output directories, the first usually goes somewhere under your "content" directory for Hugo, and the second is typically in a "static" directory. You can check out an example setup [in the wiki](https://github.com/GjjvdBurg/HugoPhotoSwipe/wiki#initializing-hugophotoswipe), with an example setup [here](https://github.com/GjjvdBurg/HugoPhotoSwipe-Demo).

Hope this helps!
