### ISSUE TITLE
Error: smartcrop.DEFAULT 

### ISSUE THREAD

**Issue by mingsu** [GjjvdBurg/HugoPhotoSwipe#28]
<img width="877" alt="image" src="https://user-images.githubusercontent.com/3145794/52818227-20f1c080-30e1-11e9-90be-9eae5088b13c.png">

**Comment by GjjvdBurg** [comment]
Thanks for the bug report! It seems that SmartCrop.py has been updated to a new API. I'll have to update the code to match this.

**Comment by GjjvdBurg** [comment]
Fixed in version 0.2.3, please update HugoPhotoSwipe and try again.
