### ISSUE TITLE
Preserve thumbnail aspect ratio? 

### ISSUE THREAD

**Issue by iammatthias** [GjjvdBurg/HugoPhotoSwipe#3]
Is there a way to change the thumbnail aspect ratio? I'd like to preserve the aspect ratio of the original image for a visually interesting grid.

**Comment by GjjvdBurg** [comment]
This is now added in version 0.0.7. There are two options added to the ``hugophotoswipe.yml`` file: ``square_thumbnails`` and ``square_coverimage``. They are set to True by default but changing them to False will give the same behavior as the other resizing, except that SmartCrop will still be used.

Hope this helps, let me know if you encounter any other issues!

**Comment by iammatthias** [comment]
Thank you!
