### ISSUE TITLE
minor edits to wiki

### ISSUE THREAD

**Issue by CouldBeThis** [GjjvdBurg/HugoPhotoSwipe#38]
Hi, While I was reading your wiki I made some minor edits basically for legibility. But it seems there is actually no way to make a PR for a wiki. So if you want, here is a zip of the file + `.git` with commit history. Sorry not sure if there is a better way?

[HugoPhotoSwipe.wiki.zip](https://github.com/GjjvdBurg/HugoPhotoSwipe/files/7609771/HugoPhotoSwipe.wiki.zip)

Summary of changes:
 - `$` from the beginning of code blocks where they were there by mistake
 - changed lists of files to be vertical instead of horizontal (easier to read) or used `tree` to display complete structure.
    - I assume in the section about copying files from PhotoSwipe repo you intended for the image files to be included  along with CSS and JS  so that's what is written
 - made one tiny content change in "Adding our first album" to clarify something that tripped me up. 

(I did *not* make any change to reflect #37 because I don't know if my solution is very good.) 

If updating this way is too much of a PITA then just close/ignore, you won't hurt my feelings. Just that I'd already done it the work.

**Comment by GjjvdBurg** [comment]
Thanks @CouldBeThis! This is very much appreciated! :+1:

It'll take a few days before I can make time to look into this and the other issue in more detail, but I appreciate your help!

**Comment by CouldBeThis** [comment]
I saw the wiki is actually inside this repo in /docs. Not sure if they are are actually the same file or one creates the other or...? At any rate will give it a shot this way. 

I just copied and pasted the end result. All my careful change tracking is lost. :( If you need that you still have to look in the zip. It is very straightforward however so doubtful.

**Comment by GjjvdBurg** [comment]
Thanks @CouldBeThis! I think this can be closed now because #39 is merged, but if I'm wrong please reopen it.
