### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by catkfr** [GjjvdBurg/HugoPhotoSwipe#4]
Hi,

I wasn't able to install hps without a prior installation of smartcrop. Maybe the readme could be amended:

This works within a clean virtualenv:
```
bin/pip install --upgrade git+https://github.com/hhatto/smartcrop.py.git
bin/pip install hugophotoswipe
```

This is the output from trying to install hps in a clean virtualenv:
```
bin/pip install hugophotoswipe
Collecting hugophotoswipe
  Downloading hugophotoswipe-0.0.7.tar.gz
Collecting six (from hugophotoswipe)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting tzlocal (from hugophotoswipe)
  Downloading tzlocal-1.3.tar.gz
Collecting pytz (from hugophotoswipe)
  Downloading pytz-2016.10-py2.py3-none-any.whl (483kB)
Collecting smartcrop>=0.1 (from hugophotoswipe)
  Could not find a version that satisfies the requirement smartcrop>=0.1 (from hugophotoswipe) (from versions: )
No matching distribution found for smartcrop>=0.1 (from hugophotoswipe)
```

Regards,

catkfr

**Comment by catkfr** [comment]
In order to actually run hps init, you also need to additional packages:
```
pip install PyYAML
pip install tqdm
```

**Comment by GjjvdBurg** [comment]
Updated this in version 0.0.8. The ``--process-dependency-links`` flag is needed apparently to get pip to install dependencies from Github when installing from PyPI. The readme has been updated to reflect this.
