### ISSUE TITLE
`hps init` failing if not run in clean directory

### ISSUE THREAD

**Issue by rossgray** [GjjvdBurg/HugoPhotoSwipe#5]
Just a small idea for improvement: from the usage instructions it was not clear to me that `hps init` needs to be ran in a new directory:

> First, initialize a new HugoPhotoSwipe directory with: `hps init`

This sounds like the `hps init` command will initialize the new directory for me. So when I ran `hps init` in an existing Hugo repo the command failed.

Perhaps it would be a good idea for the init script to check if it is being ran in a clean directory and if not, return an error to the user?

**Comment by GjjvdBurg** [comment]
Thanks for checking out HugoPhotoSwipe! I've updated the instructions and added support for skipping non-album directories in version 0.0.9.
