### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by catkfr** [GjjvdBurg/HugoPhotoSwipe#7]
Hi,

I really want to make HPS work on my system: it's exactly what I want! Thanks for building it.

I'm having difficulties trying HPS out. I feel some clarifications in the documentation could help.

In particular, having a complete example of a proper working `hugophotoswipe.yml` would be very helpful in my clumsy attempts to guess the proper way to set each variable.

We solved the issues for dependencies (previous issue): thanks.

I have hps installed in a virtualenv and am trying to create a first gallery. For the moment, I just want to see a result and defined nothing in the `url_prefix:` of the `hugophotoswipe.yml`

This generates an error when running `hps update`:
```
Traceback (most recent call last):
  File "hps8/bin/hps", line 12, in <module>
    sys.exit(main())
  File "hps8/lib/python3.6/site-packages/hugophotoswipe/ui.py", line 23, in main
    hps.update(name=album)
  File "hps8/lib/python3.6/site-packages/hugophotoswipe/hugophotoswipe.py", line 58, in update
    album.update()
  File "hps8/lib/python3.6/site-packages/hugophotoswipe/album.py", line 256, in update
    self.create_markdown()
  File "hps8/lib/python3.6/site-packages/hugophotoswipe/album.py", line 132, in create_markdown
    txt.append(photo.shortcode)
  File "hps8/lib/python3.6/site-packages/hugophotoswipe/photo.py", line 326, in shortcode
    self.large_path[len(settings.output_dir):])
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Then it was issues with directory naming. To test, I had specified:
```
markdown_dir: md
output_dir: output
photo_dir: photos
```

Those didn't work either causing a crash (because no backslash at the end?). I now imagine that it would be better to specify complete paths...

I also stumbled on smartcrop.js configuration. First I want to manage to successfully create a gallery but once again, a short clarification in the documentation (to install smartcrop.js then configure the .yml file) for newbies such as myself would be a great help.

Looking ahead, I wonder what you recommend in terms of including this in a hugo website.
- Should the output be set in the static directory? Is this a pre-requisite given your choice to use "url-prefix"?
- Should the md directory be somewhere in the content folder? I think for my personal site, I'll have content/post and content/gallery to have two separate categories created by hugo. How do you do it?
- I also took a look in the `docs/readme.md`. Given my current proficiency with hugo, I don't understand what I need to do. I think you suggest to create two files in the layout/shortcodes directory, a javascript file. If these files should be used as is, why not just create these files somewhere in the HPS repository and in the documentation just tell us where we should put them?
- Concerning the Photoswipe HTML block, I don't understand what I should do with it? Create a file? include it in a pre-existing file?

I imagine these questions may seem quite trivial to you, but for me, they are not. I  hope these comments will help you make this package more newbie-friendly and enjoy a wider user base.

Regards,

catkfr

**Comment by GjjvdBurg** [comment]
Hi, thanks for checking out HugoPhotoSwipe! I'll try to put some more detailed instructions online this week. In the meantime, perhaps my [blog post](https://gertjanvandenburg.com/blog/hugophotoswipe/) can be helpful too. Also, make sure you're using the latest version of HugoPhotoSwipe:

    pip install --upgrade --process-dependency-links hugophotoswipe

**Comment by GjjvdBurg** [comment]
@catkfr Please check out the Wiki page, this now contains a walkthrough on how to setup a Hugo site and HugoPhotoSwipe. I'll add a section on using SmartCrop.js later, but this should get you started.

**Comment by catkfr** [comment]
@GjjvdBurg Thanks for all this! It's a lot clearer for me!
I have now a working hps configuration which is great.

Now I need to understand how to integrate the hugo configuration in my current setup: I am using a tweeked version of the casper theme.
Just to see how hugo would react, I tried to putting the files in the root layout directory but that didn't work. I think I need to integrate everything in the theme.

**Comment by GjjvdBurg** [comment]
@catkfr Glad it helped! I've just added some info about how to use SmartCrop.js to the Wiki. This is still optional to use of course. The demo page corresponding to the wiki also works now ([link](https://gjjvdburg.github.io/HugoPhotoSwipe-Demo/)).

Yes, using PhotoSwipe in your theme will probably require some manual rewriting. The [Hugo docs](https://gohugo.io/overview/introduction/) should be a good resource for help with that. Good luck!
